### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by asdint** [wojiaojiao/pegasus_gazebo_plugins#1]
您好我按照步骤，直接把那几行程序放到了urdf程序后面，打开gazebo后和之前相比没有变化，下面是我的程序（我没有截取全部，仅给出了最后的部分）
  <joint
    name="Joint_2_5"
    type="revolute">
    <origin
      xyz="0.15 -0.045 0.345"
      rpy="-1.5708 -1.4555 -3.1416" />
    <parent
      link="2_Link" />
    <child
      link="5_Link" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-1.57"
      upper="1.57"
      effort="0"
      velocity="0" />
  </joint>

     < gazebo >
       < plugin  name = " Myrobot_ClosedLoopPlugin "  filename = " libpegasus_gazebo_closed_loop_plugin.so " >
           < joint > Joint_5_6 </ joint >
           < child > 6_link </ child >
           < parent > 5_link </ parent >
       </ plugin >
     </ gazebo >

</robot>

**Comment by wojiaojiao** [comment]
是不是你连接的位置要改一下呢？
in closed_loop_plugin.cpp

math::Pose jointOrigin(x,y,z,roll,pitch,yaw);

math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);

**Comment by wojiaojiao** [comment]
你在closed_loop_plugin.cpp
找到这行代码：
math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);
然后把连接的位置改一下，编译之后再运行看看

**Comment by asdint** [comment]
这个位置是值得joint的位置吗？


 
---原始邮件---
发件人: "Angel_jj"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:19
收件人: "wojiaojiao/pegasus_gazebo_plugins"<pegasus_gazebo_plugins@noreply.github.com>;
抄送: "asdint"<873223505@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wojiaojiao/pegasus_gazebo_plugins] 求助 (#1)



你在closed_loop_plugin.cpp
 找到这行代码：
 math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);
 然后把连接的位置改一下，编译之后再运行看看

**Comment by asdint** [comment]
我不太明白这个位置要改成什么位置，如果改成joint的位置，我并不知道增加的joint的具体位置


 
---原始邮件---
发件人: "Angel_jj"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:19
收件人: "wojiaojiao/pegasus_gazebo_plugins"<pegasus_gazebo_plugins@noreply.github.com>;
抄送: "asdint"<873223505@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wojiaojiao/pegasus_gazebo_plugins] 求助 (#1)



你在closed_loop_plugin.cpp
 找到这行代码：
 math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);
 然后把连接的位置改一下，编译之后再运行看看

**Comment by wojiaojiao** [comment]
那你可以先改x坐标试试，看看有没有效果

**Comment by wojiaojiao** [comment]
这个插件的作用就是相当于把两个6_link 和5_link这两个杆粘起来，math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);这个代表沾的位置，如果你改这个没有起作用，那就说明这个插件根本没起作用，是别的问题，你先试试，把这个排查下先

**Comment by asdint** [comment]
没有变化，joint都没有


 
---原始邮件---
发件人: "Angel_jj"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:23
收件人: "wojiaojiao/pegasus_gazebo_plugins"<pegasus_gazebo_plugins@noreply.github.com>;
抄送: "asdint"<873223505@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wojiaojiao/pegasus_gazebo_plugins] 求助 (#1)



那你可以先改x坐标试试，看看有没有效果

**Comment by asdint** [comment]
看来是插件没起作用


 
---原始邮件---
发件人: "Angel_jj"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:28
收件人: "wojiaojiao/pegasus_gazebo_plugins"<pegasus_gazebo_plugins@noreply.github.com>;
抄送: "asdint"<873223505@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wojiaojiao/pegasus_gazebo_plugins] 求助 (#1)



这个插件的作用就是相当于把两个6_link 和5_link这两个杆粘起来，math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);这个代表沾的位置，如果你改这个没有起作用，那就说明这个插件根本没起作用，是别的问题，你先试试，把这个排查下先

**Comment by asdint** [comment]
还有一点，我加上这几行代码后，rviz中显示不出来我的模型


 
---原始邮件---
发件人: "Angel_jj"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午3:28
收件人: "wojiaojiao/pegasus_gazebo_plugins"<pegasus_gazebo_plugins@noreply.github.com>;
抄送: "asdint"<873223505@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wojiaojiao/pegasus_gazebo_plugins] 求助 (#1)



这个插件的作用就是相当于把两个6_link 和5_link这两个杆粘起来，math::Pose jointOrigin(0.00,0.00,0.00,0.00,-0.00,0.00);这个代表沾的位置，如果你改这个没有起作用，那就说明这个插件根本没起作用，是别的问题，你先试试，把这个排查下先

**Comment by wojiaojiao** [comment]
你把
 < gazebo >
   < plugin  name = " Myrobot_ClosedLoopPlugin "  filename = " libpegasus_gazebo_closed_loop_plugin.so " >
       < joint > Joint_5_6 </ joint >
       < child > 6_link </ child >
       < parent > 5_link </ parent >
   </ plugin >
 </ gazebo >

加在</robot>里面，不是直接加在最后面

**Comment by wojiaojiao** [comment]
你把
< gazebo >
< plugin name = " Myrobot_ClosedLoopPlugin " filename = " libpegasus_gazebo_closed_loop_plugin.so " >
< joint > Joint_5_6 </ joint >
< child > 6_link </ child >
< parent > 5_link </ parent >
</ plugin >
</ gazebo >

加在</robot>标签里面，不是直接加在最后面

**Comment by asdint** [comment]
<joint
    name="Joint_7_6"
    type="revolute">
    <origin
      xyz="-0.17 0 0.101"
      rpy="-6.4408E-18 -5.2682E-17 0.32316" />
    <parent
      link="7_Link" />
    <child
      link="6_Link" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1.57"
      upper="1.57"
      effort="0"
      velocity="0" />
  </joint>


  < gazebo >
       < plugin  name = " Myrobot_ClosedLoopPlugin "  filename = " libpegasus_gazebo_closed_loop_plugin.so " >
           < joint > Joint_5_6 </ joint >
           < child > 6_link </ child >
           < parent > 5_link </ parent >
       </ plugin >
  </ gazebo >



  <link
    name="5_Link">
    <inertial>
      <origin
        xyz="0.00597365708598141 0.0372097626114086 -0.0284817379347532"
        rpy="0 0 0" />
      <mass

**Comment by asdint** [comment]
我把他放到靠上一些的位置了
还是那样   joint_5_6没有

**Comment by wojiaojiao** [comment]
5_Link 你这个是大写的L?

**Comment by asdint** [comment]
小写的

**Comment by wojiaojiao** [comment]
我看你的urdf里面这是 5_Link 是大写的L

**Comment by asdint** [comment]
我看下  好像是有点不统一

**Comment by asdint** [comment]
有意思的是  我改成5_LInk后  在打开gazebo  5_Link就消失了

**Comment by asdint** [comment]
[ERROR] [1557820335.933277117]: Error reading end tag.
process[rviz-4]: started with pid [14990]
[robot_state_publisher-3] process has died [pid 14989, exit code 255, cmd /opt/ros/kinetic/lib/robot_state_publisher/state_publisher __name:=robot_state_publisher __log:=/home/gao/.ros/log/308836e2-761d-11e9-93d3-8c1645e4c04c/robot_state_publisher-3.log].
log file: /home/gao/.ros/log/308836e2-761d-11e9-93d3-8c1645e4c04c/robot_state_publisher-3*.log
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 474, in <module>
    jsp = JointStatePublisher()
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 149, in __init__
    robot = xml.dom.minidom.parseString(description)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 451, column 3
[joint_state_publisher-2] process has died [pid 14988, exit code 1, cmd /opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher __name:=joint_state_publisher __log:=/home/gao/.ros/log/308836e2-761d-11e9-93d3-8c1645e4c04c/joint_state_publisher-2.log].
log file: /home/gao/.ros/log/308836e2-761d-11e9-93d3-8c1645e4c04c/joint_state_publisher-2*.log

**Comment by asdint** [comment]
rviz显示这个错误

**Comment by asdint** [comment]
一开始不成功是因为我写错了link的名称，后来改正过来不行，可能是因为我的系统问题吧  ，然后今天按照教程又试了一次，就成功了，所以程序是没有问题的，大家放心使用！
