### ISSUE TITLE
plugin not work..

### ISSUE THREAD

**Issue by calm0815** [wojiaojiao/pegasus_gazebo_plugins#9]
Hello, Angel.
I think this is a very nice and useful plugin.

I also want to implement this plugin in my robot (echo_bot), but I'm having trouble implementing it as expected.

## Operating Environment:

- Ubuntu 18.04
- ROS melodic
- Gazebo 9

## Related Packages:

- [echo_bot_common(branch : dev/add_transmission)](https://github.com/calm0815/echo_bot_common/tree/dev/add_transmision)
- [echo_bot_simulator(branch : develop)](https://github.com/calm0815/echo_bot_simulator/tree/develop)
- pegasus_gazebo_plugins <- it's for Gazebo 9

## What I've Been To:

1. I cloned and built this plugin (version 9.0).
2. Added plugin settings in robot tag. -> [here](https://github.com/calm0815/echo_bot_common/blob/071e464fafe5e01b59954e780d6ff04cdc342277/echo_bot_description/robots/echo_bot.urdf.xacro#L63-L81)
3. I started gazebo with 
`roslaunch echo_bot_gazebo test.launch`
4. As shown in the following image, the closed link set in 2 was not properly closed.
![Screenshot from 2020-04-18 17-39-08](https://user-images.githubusercontent.com/26988372/79632635-8fc22200-819b-11ea-81ca-ffb8e6e0bb7a.png)
5. I checked on Gazebo's screen to make sure the plugin loaded correctly. → It was a success.

**note** : You can see the robot with the joints connected correctly on Rviz.
`roslaunch echo_bot_description display_echo_bot.launch`

## QUESTION:

I couldn't find out what's wrong with my URDF.
What is the correct way to write your plugin to use it?

**Comment by 2b-t** [comment]
Hey @calm0815!
I had the same issue and found out that there is no need to use this tool, you can also **directly inject SDF-code** for the last joint in a URDF file that closes an open kinematic chain to a closed loop. I have written a small example and tutorial [here](https://github.com/2b-t/closed_loop).

**Comment by wojiaojiao** [comment]
@calm0815  do you catkin_make ?
the <position> or <rotation> is correct

**Comment by wojiaojiao** [comment]
@calm0815 do you catkin_make ?
the position or rotation is correct

**Comment by calm0815** [comment]
Thank you for your help !!

Finally, I have developed a robot with closed chain kinematics by the means @2b-t  have shown.

- movie
https://twitter.com/calm0815/status/1254786634635071494

- repo
https://github.com/calm0815/echo_bot_pkgs

@wojiaojiao 
sorry, I couldn't use your plugin.
I did catkin_make and set correct parameter.
But it doesn't worked..
